-- CreateTable
CREATE TABLE "users" ("id" TEXT NOT NULL, "auth_provider_id" TEXT, "name" VARCHAR(80) NOT NULL, "email" VARCHAR(320) NOT NULL, "role" VARCHAR(120) NOT NULL, "plan" TEXT NOT NULL, "level" INTEGER NOT NULL DEFAULT 1, "timezone" VARCHAR(80) NOT NULL DEFAULT 'UTC', "streak_days" INTEGER NOT NULL DEFAULT 0, "skills_mastered" INTEGER NOT NULL DEFAULT 0, "tasks_completed" INTEGER NOT NULL DEFAULT 0, "joined_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updated_at" TIMESTAMP(3) NOT NULL, CONSTRAINT "users_pkey" PRIMARY KEY ("id"));
CREATE TABLE "courses" ("id" TEXT NOT NULL, "title" VARCHAR(160) NOT NULL, "category" VARCHAR(80) NOT NULL, "description" TEXT NOT NULL, "level" TEXT NOT NULL, "duration_minutes" INTEGER NOT NULL, "lesson_count" INTEGER NOT NULL, "published" BOOLEAN NOT NULL DEFAULT false, "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updated_at" TIMESTAMP(3) NOT NULL, CONSTRAINT "courses_pkey" PRIMARY KEY ("id"));
CREATE TABLE "enrollments" ("id" TEXT NOT NULL, "user_id" TEXT NOT NULL, "course_id" TEXT NOT NULL, "active" BOOLEAN NOT NULL DEFAULT false, "progress_percent" INTEGER NOT NULL DEFAULT 0, "current_module" VARCHAR(200) NOT NULL, "enrolled_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updated_at" TIMESTAMP(3) NOT NULL, CONSTRAINT "enrollments_pkey" PRIMARY KEY ("id"));
CREATE TABLE "practice_sessions" ("id" TEXT NOT NULL, "user_id" TEXT NOT NULL, "course_id" TEXT, "minutes" INTEGER NOT NULL, "started_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "practice_sessions_pkey" PRIMARY KEY ("id"));
CREATE TABLE "notifications" ("id" TEXT NOT NULL, "user_id" TEXT NOT NULL, "message" TEXT NOT NULL, "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "read_at" TIMESTAMP(3), CONSTRAINT "notifications_pkey" PRIMARY KEY ("id"));
CREATE TABLE "activities" ("id" TEXT NOT NULL, "user_id" TEXT NOT NULL, "title" VARCHAR(160) NOT NULL, "detail" TEXT NOT NULL, "kind" TEXT NOT NULL, "occurred_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "activities_pkey" PRIMARY KEY ("id"));
CREATE TABLE "chat_threads" ("id" TEXT NOT NULL, "user_id" TEXT NOT NULL, "course_id" TEXT, "title" VARCHAR(160), "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updated_at" TIMESTAMP(3) NOT NULL, CONSTRAINT "chat_threads_pkey" PRIMARY KEY ("id"));
CREATE TABLE "chat_messages" ("id" TEXT NOT NULL, "thread_id" TEXT NOT NULL, "role" TEXT NOT NULL, "text" TEXT NOT NULL, "provider" VARCHAR(40), "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "chat_messages_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX "users_auth_provider_id_key" ON "users"("auth_provider_id");
CREATE UNIQUE INDEX "users_email_key" ON "users"("email");
CREATE UNIQUE INDEX "enrollments_user_id_course_id_key" ON "enrollments"("user_id", "course_id");
CREATE INDEX "enrollments_user_id_active_idx" ON "enrollments"("user_id", "active");
CREATE INDEX "practice_sessions_user_id_started_at_idx" ON "practice_sessions"("user_id", "started_at" DESC);
CREATE INDEX "notifications_user_id_created_at_idx" ON "notifications"("user_id", "created_at" DESC);
CREATE INDEX "activities_user_id_occurred_at_idx" ON "activities"("user_id", "occurred_at" DESC);
CREATE INDEX "chat_messages_thread_id_created_at_idx" ON "chat_messages"("thread_id", "created_at");
CREATE UNIQUE INDEX "one_active_enrollment_per_user" ON "enrollments"("user_id") WHERE "active" = true;
CREATE TYPE "Plan" AS ENUM ('Free', 'Premium');
CREATE TYPE "CourseLevel" AS ENUM ('Beginner', 'Intermediate', 'Advanced');
CREATE TYPE "ActivityKind" AS ENUM ('lesson', 'practice', 'achievement');
CREATE TYPE "ChatRole" AS ENUM ('student', 'tutor');
ALTER TABLE "users" ALTER COLUMN "plan" TYPE "Plan" USING "plan"::"Plan";
ALTER TABLE "courses" ALTER COLUMN "level" TYPE "CourseLevel" USING "level"::"CourseLevel";
ALTER TABLE "activities" ALTER COLUMN "kind" TYPE "ActivityKind" USING "kind"::"ActivityKind";
ALTER TABLE "chat_messages" ALTER COLUMN "role" TYPE "ChatRole" USING "role"::"ChatRole";
ALTER TABLE "users" ADD CONSTRAINT "users_level_check" CHECK ("level" >= 1), ADD CONSTRAINT "users_streak_days_check" CHECK ("streak_days" >= 0), ADD CONSTRAINT "users_skills_mastered_check" CHECK ("skills_mastered" >= 0), ADD CONSTRAINT "users_tasks_completed_check" CHECK ("tasks_completed" >= 0);
ALTER TABLE "courses" ADD CONSTRAINT "courses_duration_minutes_check" CHECK ("duration_minutes" > 0), ADD CONSTRAINT "courses_lesson_count_check" CHECK ("lesson_count" > 0);
ALTER TABLE "enrollments" ADD CONSTRAINT "enrollments_progress_percent_check" CHECK ("progress_percent" BETWEEN 0 AND 100);
ALTER TABLE "practice_sessions" ADD CONSTRAINT "practice_sessions_minutes_check" CHECK ("minutes" BETWEEN 1 AND 480);
ALTER TABLE "enrollments" ADD CONSTRAINT "enrollments_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "enrollments" ADD CONSTRAINT "enrollments_course_id_fkey" FOREIGN KEY ("course_id") REFERENCES "courses"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "practice_sessions" ADD CONSTRAINT "practice_sessions_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "practice_sessions" ADD CONSTRAINT "practice_sessions_course_id_fkey" FOREIGN KEY ("course_id") REFERENCES "courses"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "notifications" ADD CONSTRAINT "notifications_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "activities" ADD CONSTRAINT "activities_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "chat_threads" ADD CONSTRAINT "chat_threads_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "chat_threads" ADD CONSTRAINT "chat_threads_course_id_fkey" FOREIGN KEY ("course_id") REFERENCES "courses"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "chat_messages" ADD CONSTRAINT "chat_messages_thread_id_fkey" FOREIGN KEY ("thread_id") REFERENCES "chat_threads"("id") ON DELETE CASCADE ON UPDATE CASCADE;
